#define EPI 0
#define MNI 1

#define CCA 0
#define GLM 1

#define SILENT 0
#define VERBOSE 1

#define NO 0
#define YES 1

#define RAW 0
#define NIFTI 1

#define DISCARD_DISPLACEMENT_FIELD 0
#define KEEP_DISPLACEMENT_FIELD 1

#define FLOAT 0
#define INT32 1
#define INT16 2
#define UINT32 3
#define UINT16 4
#define DOUBLE 5
#define UINT8 6

#define SLICE_TIMING_CORRECTION 0
#define MOTION_CORRECTION 1
#define SMOOTHING 2
#define DETRENDING 3
#define STATISTICAL_ANALYSIS 4
#define PERMUTATION_TEST 5
#define COPY 6
#define CONVOLVE 7
#define PHASEDC 8
#define PHASEG 9
#define AH2D 10
#define EQSYSTEM 11
#define INTERPOLATION 12

#define DONT_CALCULATE_VOXEL_LABELS 0
#define CALCULATE_VOXEL_LABELS 1

#define DONT_CALCULATE_CLUSTER_MASS 0
#define CALCULATE_CLUSTER_MASS 1

#define VOXEL 0
#define CLUSTER_EXTENT 1
#define CLUSTER_MASS 2

#define VALID_FILTER_RESPONSES_X_SEPARABLE_CONVOLUTION_ROWS 32
#define VALID_FILTER_RESPONSES_Y_SEPARABLE_CONVOLUTION_ROWS 8
#define VALID_FILTER_RESPONSES_Z_SEPARABLE_CONVOLUTION_ROWS 8

#define VALID_FILTER_RESPONSES_X_SEPARABLE_CONVOLUTION_COLUMNS 24
#define VALID_FILTER_RESPONSES_Y_SEPARABLE_CONVOLUTION_COLUMNS 16
#define VALID_FILTER_RESPONSES_Z_SEPARABLE_CONVOLUTION_COLUMNS 8

#define VALID_FILTER_RESPONSES_X_SEPARABLE_CONVOLUTION_RODS 32
#define VALID_FILTER_RESPONSES_Y_SEPARABLE_CONVOLUTION_RODS 8
#define VALID_FILTER_RESPONSES_Z_SEPARABLE_CONVOLUTION_RODS 8

#define NOT_SKULL_STRIPPED 1
#define SKULL_STRIPPED 0

#define HALO 3
#define VALID_FILTER_RESPONSES_X_CONVOLUTION_2D 90
#define VALID_FILTER_RESPONSES_Y_CONVOLUTION_2D 58

#define VALID_FILTER_RESPONSES_X_CONVOLUTION_2D_AMD 122
#define VALID_FILTER_RESPONSES_Y_CONVOLUTION_2D_AMD 58

#define TTEST 0
#define FTEST 1

#define DOWN 0
#define UP 1
#define DOWN_INTERLEAVED 2
#define UP_INTERLEAVED 3

#define TRANSLATION 0
#define RIGID 1
#define AFFINE 2

#define NEAREST 0
#define LINEAR 1
#define CUBIC 2

#define DO_OVERWRITE 0
#define NO_OVERWRITE 1

#define PI 3.14159265359

#define INITIAL_MM_T1_Z_CUT 15

#define SUCCESS 0

#define NVIDIA 0
#define INTEL 1
#define AMD 2

#define NUMBER_OF_FILTERS_FOR_NONPARAMETRIC_REGISTRATION 6
